name: Test xjs build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install dependencies and run linters
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pycodestyle
        pip install -r requirements.txt
        pycodestyle xjs
        flake8 xjs

    - name: Run xjs tests
      run: |
        python3 xjs examples/example.json
        python3 xjs examples/example.json
        python3 xjs examples/example.yaml
        python3 xjs examples/example2.yaml
        python3 xjs examples/example.json examples/example2.json
        python3 xjs --application glance examples/example.json
        python3 xjs --application rabbitmq-server examples/example.json
        python3 xjs --model k8s examples/example2.json
        python3 xjs --controller controller examples/example.json examples/example2.json
        python3 xjs --unit k8s/0 examples/example2.json
        python3 xjs --subordinate ovn-chassis/0 examples/example.json
